on:
  push:
    branches:
      - main
      - master
      - gha

name: bookdown

jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/geospatial:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes','rmarkdown','bookdown'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

#      - name: Deploy to Netlify
#        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
#        env:
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#        run: |
#          npm install netlify-cli -g
#          netlify deploy --prod --dir _book
