name: bookdown

on:
  push:
    branches:
      - main
      - master
      - gha #temporary

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # container:
    #   image: inseefrlab/utilitr:latest # your docker image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
     # - name: Add apt install
     #   run: |
     #     apt-get install software-properties-common

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

     - name: Install pandoc and pandoc citeproc
       run: |
         brew install pandoc
         brew install pandoc-citeproc

     - name: Cache Renv packages
       uses: actions/cache@v2
       with:
         path: $HOME/.local/share/renv
         key: r-${{ hashFiles('renv.lock') }}
         restore-keys: r-

     - name: Cache bookdown results
       uses: actions/cache@v2
       with:
         path: _bookdown_files
         key: bookdown-${{ hashFiles('**/*Rmd') }}
         restore-keys: bookdown-

     - name: Install packages
       run: |
         R -e 'install.packages("renv")'
         R -e 'renv::restore()'

      - name: Build site
        run: |
          R -e 'install.packages("knitr")'
          R -e 'remotes::install_deps(dependencies = TRUE, upgrade = FALSE)'
          R -e 'bookdown::render_book("index.Rmd", output_format = 'all', output_dir = '_public')'

      - name: Install npm
        uses: actions/setup-node@v1

#      - name: Deploy to Netlify
#        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
#        env:
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#        run: |
#          npm install netlify-cli -g
#          netlify deploy --prod --dir _book
